# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      # Execute build
      - name: Build
        run: ./gradlew clean build
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew clean test

  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Execute scan
      - name: SonarCloud Scan
      - uses: SonarSource/sonarcloud-github-action@v1.5

